server:
  port: 9000

spring:
  servlet:
    multipart:
      max-file-size: 60MB
      max-request-size: 60MB
      enabled: true
  security:
    csrf:
      enabled: false
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://127.0.0.1:4200"
            allowedHeaders: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE

---

spring:
  security:
    csrf:
      enabled: false
  config:
    activate:
      on-profile: development
  cloud:
    gateway:
      routes:
        - id: usersManagement
          uri: http://users-management:8080/
          predicates:
            - Path=/api/**
        - id: modelService
          uri: http://django-model:9004/
          predicates:
            - Path=/model/**
          filters:
            - AuthenticationFilter
        - id: resultsServer
          uri: http://django-query:8000/
          predicates:
            - Path=/queries/**
          filters:
            - AuthenticationFilter